# Generated by Django 3.0.4 on 2020-04-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavedata',
            name='app_id',
        ),
    ]
