# Generated by Django 3.0.4 on 2020-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0005_leavedata_manager_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Background_Verification',
            field=models.CharField(choices=[('1', 'Done'), ('2', 'NotDone'), ('0', 'InProgress')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='Offer_Later',
            field=models.CharField(choices=[('1', 'Provided'), ('2', 'NotProvided')], default=None, max_length=2),
        ),
    ]
