# Generated by Django 3.0.4 on 2020-04-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0006_auto_20200422_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Offer_Later',
            new_name='Offer_Latter',
        ),
    ]
