# Generated by Django 3.0.4 on 2020-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0007_auto_20200429_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Festival_Name', models.CharField(choices=[('1', 'Republic Day'), ('2', 'Holi'), ('3', 'Good Friday'), ('4', 'Independence Day'), ('5', 'Rakshabandhan'), ('6', 'Gandhi Jayanti'), ('7', 'Dashera'), ('8', 'Deepawali'), ('9', 'Christmas')], max_length=30)),
                ('Type', models.CharField(choices=[('1', 'Holiday'), ('2', 'Restricted Holiday'), ('3', 'National Holiday')], max_length=20)),
            ],
        ),
    ]
