# Generated by Django 3.0.4 on 2020-04-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0008_company_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_holiday',
            name='Festival_Name',
            field=models.CharField(choices=[('Republic Day', '1'), ('Holi', '2'), ('Good Friday', '3'), ('Independence Day', '4'), ('Rakshabandhan', '5'), ('Gandhi Jayanti', '6'), ('Dashera', '7'), ('Deepawali', '8'), ('Christmas', '9')], max_length=30),
        ),
    ]
