# Generated by Django 3.0.4 on 2020-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0009_auto_20200430_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_holiday',
            name='Festival_Name',
            field=models.CharField(choices=[('1', 'Republic Day'), ('2', 'Holi'), ('3', 'Good Friday'), ('4', 'Independence Day'), ('5', 'Rakshabandhan'), ('6', 'Gandhi Jayanti'), ('7', 'Dashera'), ('8', 'Deepawali'), ('9', 'Christmas')], max_length=30),
        ),
    ]
