# Generated by Django 3.0.4 on 2020-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0010_auto_20200430_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_holiday',
            name='Festival_Name',
            field=models.CharField(choices=[('Republic Day', 'Republic Day'), ('Holi', 'Holi'), ('Good Friday', 'Good Friday'), ('Independence Day', 'Independence Day'), ('Rakshabandhan', 'Rakshabandhan'), ('Gandhi Jayanti', 'Gandhi Jayanti'), ('Dashera', 'Dashera'), ('Deepawali', 'Deepawali'), ('Christmas', 'Christmas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='company_holiday',
            name='Type',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Restricted Holiday', 'Restricted Holiday'), ('National Holiday', 'National Holiday')], max_length=20),
        ),
    ]
