# Generated by Django 3.0.4 on 2020-05-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0012_currentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Contact', models.CharField(max_length=12)),
                ('From_Date', models.DateField()),
                ('To_Date', models.DateField()),
                ('Project_Name', models.CharField(max_length=60)),
                ('Department', models.CharField(max_length=30)),
                ('Reason', models.CharField(max_length=200)),
                ('No_Days', models.IntegerField()),
                ('Apply_Date', models.DateField(auto_now=True)),
                ('Manager_Remark', models.CharField(default='Pending', max_length=20)),
                ('Manager_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leave.Manager')),
            ],
        ),
    ]
